name: SSH Deployment

on:
  push:
    branches:
      - master
      - github-actions
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    name: 
    steps:
    - name: Install dependencies
      run: npm install
    - name: Fix audits
      run: npm audit fix --force
    - name: Build PWA
      run npm run build
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" /build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/volume1/web/
